language: node_js
sudo: false
node_js:
  - 11.13.0

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

restore_cache:
  name: Restore Yarn Package Cache
  keys:
    - yarn-packages-{{ checksum "yarn.lock" }}
install:
  - yarn install --frozen-lockfile
save_cache:
  name: Save Yarn Package Cache
  key: yarn-packages-{{ checksum "yarn.lock" }}
  paths:
    - ~/.cache/yarn

stages:
  - test
  - build
  - lint
  
jobs:
  include:
    - stage: test
      script: yarn test:coveralls
    - script: yarn typecheck
    - script: yarn prettier:check
    - script: yarn lint
    - stage: build
      script: yarn build
    - stage: build docker
      script: skip
      deploy:
        provider: script
        script: bash server/test.sh
        on:
          branch: master
