language: node_js
sudo: false
node_js:
  - 11.13.0
install:
  - yarn install
stages:
  - test
  - build
  - lint
jobs:
  include:
    - stage: test
      script: yarn test:coveralls
    - script: yarn prettier:check
    - script: yarn lint
    - stage: build
      script: yarn build
    - stage: build docker
      script: skip
      deploy:
        provider: script
        script: "
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push bingneef/hello-nextjs"
        on: branch: master
